import {
  CargoStatus,
  CustomsStatus,
  type CargoPackageCheckData,
} from './types';

const baseData: CargoPackageCheckData = {
  flow: {
    title: 'Cargo package handover',
    hblNumber: 'HBL-778899',
    workingStatus: 'in-progress',
  },
  packages: [
    {
      id: 'pkg-001',
      packageNo: 'PKG-001',
      packingListId: 'PL-1001',
      hblNumber: 'HBL-778899',
      lineId: 'line-1',
      lineNo: 1,
      cargoDescription: 'Textile rolls',
      cargoType: 'Textile',
      cargoUnit: 'Roll',
      packageType: 'Pallet',
      cargoStatus: CargoStatus.Normal,
      customsStatus: CustomsStatus.Uninspected,
      isChecked: false,
      checkedDate: null,
    },
    {
      id: 'pkg-002',
      packageNo: null,
      packingListId: 'PL-1001',
      hblNumber: 'HBL-778899',
      lineId: 'line-1',
      lineNo: 1,
      cargoDescription: 'Textile rolls',
      cargoType: 'Textile',
      cargoUnit: 'Roll',
      packageType: 'Pallet',
      cargoStatus: null,
      customsStatus: null,
      isChecked: false,
      checkedDate: null,
    },
    {
      id: 'pkg-003',
      packageNo: 'PKG-003',
      packingListId: 'PL-1001',
      hblNumber: 'HBL-778899',
      lineId: 'line-2',
      lineNo: 2,
      cargoDescription: 'Household goods',
      cargoType: 'Home',
      cargoUnit: 'Box',
      packageType: 'Carton',
      cargoStatus: CargoStatus.CargoDamaged,
      customsStatus: CustomsStatus.OnHold,
      isChecked: true,
      checkedDate: '2024-09-01T10:00:00.000Z',
    },
    {
      id: 'pkg-004',
      packageNo: null,
      packingListId: 'PL-1002',
      hblNumber: null, // HBL may not be available yet
      lineId: 'line-3',
      lineNo: 1,
      cargoDescription: 'Electronics accessories',
      cargoType: 'Electronics',
      cargoUnit: 'CTN',
      packageType: 'Carton',
      cargoStatus: CargoStatus.Normal,
      customsStatus: CustomsStatus.Passed,
      isChecked: true,
      checkedDate: '2024-09-01T09:30:00.000Z',
    },
    {
      id: 'pkg-005',
      packageNo: 'PKG-005',
      packingListId: 'PL-1002',
      hblNumber: null,
      lineId: 'line-4',
      lineNo: 2,
      cargoDescription: 'Furniture parts',
      cargoType: 'Furniture',
      cargoUnit: 'Set',
      packageType: 'Crate',
      cargoStatus: null,
      customsStatus: null,
      isChecked: false,
      checkedDate: null,
    },
  ],
};

export async function fetchMockCargoPackageData(): Promise<CargoPackageCheckData> {
  return {
    flow: { ...baseData.flow },
    packages: baseData.packages.map(pkg => ({ ...pkg })),
  };
}
