import { type Role } from './roles';
import type { PermissionWithWildcard } from './permissions';

// Temporary role → permission mapping. Backend will later own this list.
export const ROLE_PERMISSIONS: Record<Role, PermissionWithWildcard[]> = {
  admin: ['*'],
  default: [
    'container_management:read',
    'hbl_management:read',
    'payment:read',
    'packing_list_management:read',
    'hbl_custom_clearance:read',
    'forwarder_management:read',
    'shippingline_management:read',
    'container_position_status:read',
  ],
  cfs_wh_manager: [
    'zone_and_location_management:read',
    'zone_and_location_management:write',
    'hbl_management:read',
    'hbl_management:write',
    'destuff_order_management:read',
    'destuff_order_management:write',
    'container_management:write',
    'container_receive_plan:read',
    'container_receive_plan:write',
    'destuff_plan:read',
    'destuff_plan:write',
    'actual_container_receive:read',
    'actual_container_receive:write',
    'actual_destuff:read',
    'actual_destuff:write',
    'cargo_delivery:read',
    'cargo_delivery:write',
    'cargo_package_check:read',
    'cargo_package_check:write',
    'cargo_package_store:read',
    'cargo_package_store:write',
    'cargo_package_handover:read',
    'cargo_package_handover:write',
    'packing_list_management:read',
    'packing_list_management:write',
    'hbl_custom_clearance:read',
    'hbl_custom_clearance:write',
    'forwarder_management:read',
    'forwarder_management:write',
    'shippingline_management:read',
    'shippingline_management:write',
    'container_position_status:read',
    'container_position_status:write',
    'return_empty_container:read',
    'return_empty_container:write',
    'export_service_order:read',
    'export_service_order:write',
    'cargo_package_receiving:read',
    'cargo_package_receiving:write',
    'stuffing_planning:read',
    'stuffing_planning:write',
    'stuffing:read',
    'stuffing:write',
    'inventory_check_management:read',
    'inventory_check_management:write',
    'warehouse_management:read',
    'warehouse_management:write',
    'receive_empty_container:read',
    'receive_empty_container:write',
    'move_loaded_container:read',
    'move_loaded_container:write',

  ],
  cfs_planner: [
    'zone_and_location_management:read',
    'zone_and_location_management:write',
    'destuff_order_management:read',
    'container_management:write',
    'container_receive_plan:read',
    'container_receive_plan:write',
    'destuff_plan:read',
    'destuff_plan:write',
    'packing_list_management:read',
    'packing_list_management:write',
    'hbl_custom_clearance:read',
    'hbl_custom_clearance:write',
    'forwarder_management:read',
    'forwarder_management:write',
    'shippingline_management:read',
    'shippingline_management:write',
    'container_position_status:read',
    'container_position_status:write',
    'return_empty_container:read',
    'return_empty_container:write',
    'export_service_order:read',
    'export_service_order:write',
    'cargo_package_receiving:read',
    'stuffing_planning:read',
    'stuffing_planning:write',
    'stuffing:read',
    'stuffing:write',
    'inventory_check_management:read',
    'inventory_check_management:write',
    'warehouse_management:read',
    'receive_empty_container:read',
    'receive_empty_container:write',
    'move_loaded_container:read',
    'move_loaded_container:write',
  ],
  cfs_wh_staff: [
    'actual_container_receive:read',
    'actual_container_receive:write',
    'actual_destuff:read',
    'actual_destuff:write',
    'cargo_delivery:read',
    'cargo_delivery:write',
    'cargo_package_check:read',
    'cargo_package_check:write',
    'cargo_package_store:read',
    'cargo_package_store:write',
    'cargo_package_handover:read',
    'cargo_package_handover:write',
    'cargo_package_receiving:read',
    'cargo_package_receiving:write',
    'stuffing_planning:read',
    'stuffing:read',
    'stuffing:write',
    'inventory_check_management:read',
    'inventory_check_management:write',
    'warehouse_management:read',
    'warehouse_management:write',

  ],
  cfs_gate_staff: [
    'receive_empty_container:read',
    'move_loaded_container:read',
    'return_empty_container:read',
    'return_empty_container:write',
    'move_loaded_container:check',
    'receive_empty_container:check',

  ],
  cfs_commercial: [
    'hbl_management:read',
    'hbl_management:write',
    'destuff_order_management:read',
    'destuff_order_management:write',
    'payment:read',
    'payment:write',
    'packing_list_management:read',
    'packing_list_management:write',
    'hbl_custom_clearance:read',
    'forwarder_management:read',
    'forwarder_management:write',
    'shippingline_management:read',
    'shippingline_management:write',
    'export_service_order:read',
    'export_service_order:write',
  ],
};
