// Fine-grained permissions split into read/write variants per feature.
export const BASE_PERMISSIONS = [
  'zone_and_location_management',
  'hbl_management',
  'destuff_order_management',
  'container_management',
  'container_receive_plan',
  'destuff_plan',
  'actual_container_receive',
  'actual_destuff',
  'cargo_delivery',
  'cargo_package_check',
  'cargo_package_store',
  'cargo_package_handover',
  'payment',
  'packing_list_management',
  'hbl_custom_clearance',
  'forwarder_management',
  'shippingline_management',
  'container_position_status',
  'return_empty_container',
  'export_service_order',
  'cargo_package_receiving',
  'stuffing_planning',
  'stuffing',
  'inventory_check_management',
  'warehouse_management',
  'receive_empty_container',
  'move_loaded_container',
] as const;

export type BasePermission = (typeof BASE_PERMISSIONS)[number];
export type Permission =
  | `${BasePermission}:read`
  | `${BasePermission}:write`
  | 'move_loaded_container:check'
  | 'receive_empty_container:check';
export type PermissionWithWildcard = Permission | '*';

export const PERMISSIONS: Permission[] = [
  'zone_and_location_management:read',
  'zone_and_location_management:write',
  'hbl_management:read',
  'hbl_management:write',
  'destuff_order_management:read',
  'destuff_order_management:write',
  'container_management:read',
  'container_management:write',
  'container_receive_plan:read',
  'container_receive_plan:write',
  'destuff_plan:read',
  'destuff_plan:write',
  'actual_container_receive:read',
  'actual_container_receive:write',
  'actual_destuff:read',
  'actual_destuff:write',
  'cargo_delivery:read',
  'cargo_delivery:write',
  'cargo_package_check:read',
  'cargo_package_check:write',
  'cargo_package_store:read',
  'cargo_package_store:write',
  'cargo_package_handover:read',
  'cargo_package_handover:write',
  'payment:read',
  'payment:write',
  'packing_list_management:read',
  'packing_list_management:write',
  'hbl_custom_clearance:read',
  'hbl_custom_clearance:write',
  'forwarder_management:read',
  'forwarder_management:write',
  'shippingline_management:read',
  'shippingline_management:write',
  'container_position_status:read',
  'container_position_status:write',
  'return_empty_container:read',
  'return_empty_container:write',
  'export_service_order:read',
  'export_service_order:write',
  'cargo_package_receiving:read',
  'cargo_package_receiving:write',
  'stuffing_planning:read',
  'stuffing_planning:write',
  'stuffing:read',
  'stuffing:write',
  'inventory_check_management:read',
  'inventory_check_management:write',
  'warehouse_management:read',
  'warehouse_management:write',
  'receive_empty_container:read',
  'receive_empty_container:write',
  'receive_empty_container:check',
  'move_loaded_container:read',
  'move_loaded_container:write',
  'move_loaded_container:check',
];
